export enum AuditAction {
  // User actions
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_REGISTER = 'USER_REGISTER',
  USER_PROFILE_UPDATE = 'USER_PROFILE_UPDATE',
  USER_PASSWORD_CHANGE = 'USER_PASSWORD_CHANGE',
  USER_EMAIL_VERIFY = 'USER_EMAIL_VERIFY',

  // Certificate actions
  CERTIFICATE_ISSUE = 'CERTIFICATE_ISSUE',
  CERTIFICATE_VERIFY = 'CERTIFICATE_VERIFY',
  CERTIFICATE_REVOKE = 'CERTIFICATE_REVOKE',
  CERTIFICATE_UPDATE = 'CERTIFICATE_UPDATE',
  CERTIFICATE_EXPIRE = 'CERTIFICATE_EXPIRE',
  CERTIFICATE_FREEZE = 'CERTIFICATE_FREEZE',
  CERTIFICATE_UNFREEZE = 'CERTIFICATE_UNFREEZE',
  CERTIFICATE_TRANSFER = 'CERTIFICATE_TRANSFER',

  // Issuer actions
  ISSUER_AUTHORIZE = 'ISSUER_AUTHORIZE',
  ISSUER_DEAUTHORIZE = 'ISSUER_DEAUTHORIZE',
  ISSUER_PROFILE_UPDATE = 'ISSUER_PROFILE_UPDATE',

  // Admin actions
  USER_ROLE_CHANGE = 'USER_ROLE_CHANGE',
  USER_DEACTIVATE = 'USER_DEACTIVATE',
  SYSTEM_CONFIG_UPDATE = 'SYSTEM_CONFIG_UPDATE',

  // Security events
  LOGIN_FAILED = 'LOGIN_FAILED',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',

  // System events
  BACKGROUND_JOB_START = 'BACKGROUND_JOB_START',
  BACKGROUND_JOB_COMPLETE = 'BACKGROUND_JOB_COMPLETE',
  BACKGROUND_JOB_FAILED = 'BACKGROUND_JOB_FAILED',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
}
